### ISSUE TITLE
Volleyball MEX .zip file importing 'Object reference not set to an instance of an object'

### ISSUE THREAD

**Issue by Oafish1** [akaneia/mexTool#7]
Export then import.  The other stages seem to work fine.  Volleyball, however, throws this error.  This came about when I wanted to raise the score limit and consecutive ball hit limits on the stage.  The exception text is below and the modifications were being done on .5e.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at mexTool.Core.MEXStage.InstallStageFromStream(Stream stream)
   at mexTool.Core.MEXStage.InstallStageFromFile(String filePath)
   at mexTool.GUI.Pages.StagePage.importButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at mexTool.GUI.Controls.MXButton.PerformClick()
   at mexTool.GUI.Controls.MXButton.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Oafish1** [comment]
My mistake, I didn't have the file totally closed in the hex editor.  Although I don't know how that affected a zipped version of the folder.

Additionally, on import, a 'local file header corrupt' error message is caused by overwriting another .zip file during export.
